added resumes, cover letters tabs
jobsninja/ninjasite pull request #1
Opened 2023-01-11 04:44 UTC by jomanozgml

- titles only
- next to the vacancies
![2023-01-11_15h43_23](https://user-images.githubusercontent.com/19203873/211719486-a04a783b-b1f2-4233-9266-14b4c9793194.png)

2023-01-11 05:57 UTC, kovarny requested changes
I think we talked about pages too, not just tabs. Can you create dummy pages with simple text boxes in them as well?

2023-01-12 05:19 UTC, jomanozgml commented
changes implemented
![2023-01-12_16h01_35](https://user-images.githubusercontent.com/19203873/211983655-a2a2e060-a195-4839-ad86-2771a6fc342e.png)

2023-01-13 07:06 UTC, kovarny requested changes

2023-01-13 07:06 UTC, kovarny commented on lib/search/search_page.dart
> +class ResumesPage extends ConsumerWidget {
Let's create different file for different page

2023-01-16 04:21 UTC, jomanozgml commented
Different file for different page added

2023-01-16 07:06 UTC, kovarny approved these changes

2023-01-16 07:06 UTC, merged