user vacancy list in admin page
jobsninja/ninjasite pull request #5
Opened 2023-01-20 06:39 UTC by jomanozgml

-general vacancy page at the moment
-need a fix to make specific user vacancy page and font size
![2023-01-20_17h36_13](https://user-images.githubusercontent.com/19203873/213633173-ea6745d6-f5ab-4942-92a4-afa09e1750b5.png)

2023-01-20 07:10 UTC, kovarny requested changes

2023-01-20 07:10 UTC, kovarny commented on lib/admin/user_details.dart
> +                        child: VacanciesList(),
Let's show user's own vacancies only

2023-01-24 06:50 UTC, jomanozgml commented on lib/admin/user_details.dart
> +                        child: VacanciesList(),
@kovarny requested modification done

2023-01-24 07:04 UTC, kovarny approved these changes

2023-01-24 07:04 UTC, merged